# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 77e3d89300ada7a187f5b1be63e0778e6b96927664a8fe313581e36866501d41e81ca44b2ffe999510f51a20ee967fbe4128a37c62e5fd093019caa3a33d66d6

test:
  secret_key_base: e16f8976d928f951d320d2c2f7dc57bc29f0df616b095ab946b0071062f2d0830fedd04d323002f94890acaa41a2a3935908ea07154f05c66a9c4a46305a6779

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
